"""
Content Classifier — SOTA hybrid domain + safety classification at ingest
=========================================================================

Decides for each incoming document:
  * ``corpus_domain`` ∈ {``psych``, ``general``}
  * ``safety_flag``   ∈ {``safe``, ``sensitive``, ``crisis``}

Design (pattern-/keyword-free, fully representation-learning + LLM):

  1. **Embedding-prototype primary signal for domain**
     — Mean of all L2-normalised chunk embeddings already tagged
       ``domain='psych'`` in the DB. Cosine similarity of the candidate
       text against the prototype puts the verdict on a continuous,
       auditable scale.

  2. **LLM verifier for the margin band and for safety**
     — Whenever prototype similarity falls into the configurable
       ``ambiguous_band`` (``[t_low, t_high]``), the LLM picks the
       domain.
     — The LLM is *always* consulted (when available) for ``safety_flag``,
       since safety cannot be inferred from a single positive prototype.
     — Output is Pydantic-validated, structured JSON; no free-form parsing.

  3. **SHA256-keyed persistent cache**
     — Every unique document is classified at most once across the
       lifetime of the DB. Re-ingesting the same web page or PDF is free.

  4. **Graceful degradation, never silent**
     — If the prototype cannot yet be built (psych corpus too small),
       the classifier raises if ``llm_wrapper`` is also absent. It never
       silently defaults a result it didn't actually compute.
     — Prototype-only fallback (no LLM) records ``method='prototype'``
       and ``safety_flag='safe'`` because safety cannot be detected from
       embedding distance alone — the limitation is recorded, not hidden.

Public API:
    ``ContentClassifier.classify(text, *, title=None, hint_metadata=None)
        -> ClassificationResult``
"""
from __future__ import annotations

import hashlib
import logging
import sqlite3
import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Dict, Literal, Optional, Tuple

import numpy as np
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from .database import DatabaseManager
    from .embeddings import EmbeddingManager

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
#  Pydantic schema for LLM structured output
# ─────────────────────────────────────────────────────────────────────
class _ContentClassificationLLM(BaseModel):
    """Structured LLM output for content classification.

    Both fields use ``Literal`` so the JSON Schema generated by
    ``model_json_schema()`` carries an ``enum`` constraint. When the
    wrapper compiles this schema into a GBNF grammar via
    ``LlamaGrammar.from_json_schema``, the sampler is *physically*
    restricted to emit only one of the whitelisted values — no
    Pydantic-level retry on invented domains, no thought-channel
    leakage, no unbounded string fields that would let the model loop.

    The previously-present ``reasoning`` field was removed because:
      * It was unbounded text — a string field a grammar permits to
        contain arbitrary tokens until the closing quote, which is
        exactly the surface that mode-collapse loops exploited.
      * It was never read by code; it only produced a single INFO log
        line on prototype/LLM disagreement, which is already covered
        by domain + similarity in that same log.
    """

    corpus_domain: Literal["general", "psych"] = Field(
        description="'psych' = clinical psychology, mental health, "
                    "therapy, psychiatry, psychotherapy. "
                    "'general' = everything else.",
    )
    safety_flag: Literal["safe", "sensitive", "crisis"] = Field(
        description="'safe' = ordinary content. "
                    "'sensitive' = mental-health crises, self-harm, "
                    "suicide, abuse, or trauma discussed in a clinical "
                    "or educational tone. "
                    "'crisis' = instructions, methods, or encouragement "
                    "for self-harm/suicide; must not be surfaced as RAG.",
    )


# ─────────────────────────────────────────────────────────────────────
#  Public result dataclass
# ─────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class ClassificationResult:
    corpus_domain: str
    safety_flag: str
    confidence: float
    method: str            # 'prototype' | 'llm' | 'hybrid' | 'cached' | 'explicit'
    reasoning: Optional[str] = None
    similarity: Optional[float] = None   # prototype cosine similarity if computed


_VALID_DOMAINS = {"general", "psych"}
_VALID_SAFETY = {"safe", "sensitive", "crisis"}


class LLMVerificationError(RuntimeError):
    """Raised when the LLM verifier failed to produce a valid verdict.

    Distinct from generic ``RuntimeError`` so callers (notably the
    maintenance reclassifier) can treat *transient LLM failures* — e.g.
    llama.cpp throwing a Windows C++ exception mid-decode, structured-
    output parser giving up after retries — as per-doc skips instead of
    aborting the whole sweep. Configuration errors (no prototype + no
    LLM, ambiguous band without LLM) keep raising plain ``RuntimeError``
    because retrying them is pointless.
    """

# ─────────────────────────────────────────────────────────────────────
#  Classifier version — bump on every behaviourally-relevant change
# ─────────────────────────────────────────────────────────────────────
# Read by ingest (writes ``chunks.classification_version``) and by the
# maintenance reclassifier (sweeps any chunk with a lower value).
# Bump when:
#   * thresholds change                         (PROTO_LOW / PROTO_HIGH)
#   * embedding model changes
#   * LLM prompt / Pydantic schema changes in a way that can flip outputs
#   * the valid-label sets (_VALID_DOMAINS / _VALID_SAFETY) change
CLASSIFICATION_VERSION = 2


class ContentClassifier:
    """Hybrid embedding-prototype + LLM classifier with persistent cache."""

    # ── Tuning constants ─────────────────────────────────────────────
    # Cosine-similarity thresholds against the psych-prototype.
    # Calibrated against multilingual-e5-large's output distribution:
    # psych chunks self-similarity is typically 0.7–0.85, generic web
    # text against a clinical prototype lands 0.30–0.50.
    _PROTOTYPE_SIM_LOW: float = 0.45
    _PROTOTYPE_SIM_HIGH: float = 0.62

    # Minimum number of psych-tagged chunks before the prototype is
    # trustworthy. Below this we refuse prototype mode and demand LLM.
    _MIN_PSYCH_CHUNKS: int = 50

    # Refresh prototype if the psych corpus has grown by more than this
    # fraction since the last build (cheap re-aggregation).
    _PROTOTYPE_REFRESH_GROWTH: float = 0.10

    # Cache-key construction: SHA256 over title + first N bytes of body.
    # Bounding the input keeps the hash stable when only trailing
    # navigation noise differs between two extractions of the same URL.
    _CACHE_INPUT_BYTES: int = 8000

    # LLM context window for classification call.
    _LLM_CONTEXT_BYTES: int = 4000
    # Token budget (upper bound) for the verifier response.
    #
    # With GBNF grammar constraints active (see
    # ``LLMStructuredWrapper._get_schema_grammar``), the schema's JSON
    # Schema \u2014 with its two ``Literal`` enum fields \u2014 forces a tiny
    # payload of roughly 30 tokens. This cap is therefore a defensive
    # ceiling, not a real budget; in normal operation the sampler hits
    # the closing brace and stops well before approaching it.
    _LLM_MAX_TOKENS: int = 256

    def __init__(
        self,
        embedding_manager: "EmbeddingManager",
        db_manager: "DatabaseManager",
        llm_wrapper: Optional[Any] = None,
        ambiguous_band: Optional[Tuple[float, float]] = None,
    ) -> None:
        """Args:
            embedding_manager: Required. Used to embed candidate text and
                aggregate the prototype.
            db_manager: Required. Backs the cache table and reads the
                ``chunks`` table to build the prototype.
            llm_wrapper: Optional ``LLMStructuredWrapper`` instance. If
                ``None`` the classifier degrades to prototype-only domain
                detection and always emits ``safety_flag='safe'`` with
                ``method='prototype'``.
            ambiguous_band: Optional ``(low, high)`` cosine-similarity
                band that triggers LLM domain verification. Defaults to
                ``(_PROTOTYPE_SIM_LOW, _PROTOTYPE_SIM_HIGH)``.
        """
        self._embeddings = embedding_manager
        self._db = db_manager
        self._llm = llm_wrapper

        if ambiguous_band is None:
            ambiguous_band = (self._PROTOTYPE_SIM_LOW, self._PROTOTYPE_SIM_HIGH)
        if not (0.0 <= ambiguous_band[0] < ambiguous_band[1] <= 1.0):
            raise ValueError(
                f"ContentClassifier: invalid ambiguous_band={ambiguous_band!r}; "
                "expected 0 <= low < high <= 1"
            )
        self._band_low, self._band_high = ambiguous_band

        # Prototype state (lazy + refresh-on-growth)
        self._prototype_lock = threading.RLock()
        self._psych_prototype: Optional[np.ndarray] = None
        self._psych_chunk_count: int = 0

    # ── Public API ───────────────────────────────────────────────────
    def classify(
        self,
        text: str,
        *,
        title: Optional[str] = None,
        hint_metadata: Optional[Dict[str, Any]] = None,
        conn: Optional["sqlite3.Connection"] = None,
    ) -> ClassificationResult:
        """Classify a document into ``(corpus_domain, safety_flag)``.

        Args:
            text: Full document text. Only the first
                ``_CACHE_INPUT_BYTES`` chars feed the cache key, only
                the first ``_LLM_CONTEXT_BYTES`` chars feed the LLM.
            title: Optional document title (web page <title>, PDF
                title, etc.). Concatenated with ``text`` for cache key
                and for LLM prompt context.
            hint_metadata: Reserved for future use (e.g. provenance
                hints from the producer). Currently logged only.
            conn: Optional caller-owned SQLite connection. When passed,
                cache reads/writes share that transaction — used by the
                maintenance reclassifier to avoid two-writer contention
                with its own batched UPDATEs.

        Returns:
            ClassificationResult — never ``None``, never partially
            populated. Either succeeds with a verdict or raises.

        Raises:
            ValueError: If ``text`` is empty.
            RuntimeError: If neither prototype nor LLM can produce a
                verdict (e.g. brand-new DB, no psych corpus yet, no
                LLM wired).
        """
        if not isinstance(text, str) or not text.strip():
            raise ValueError("ContentClassifier.classify: 'text' must be a non-empty string")

        cache_key = self._cache_key(text, title=title)

        # 1) Cache lookup — exact, persistent, never recomputes.
        cached = self._cache_get(cache_key, conn=conn)
        if cached is not None:
            return cached

        # 2) Prototype similarity (always when prototype exists).
        sim: Optional[float] = None
        proto_domain: Optional[str] = None
        prototype_available = self._ensure_prototype()
        if prototype_available:
            sim = self._prototype_similarity(text)
            if sim >= self._band_high:
                proto_domain = "psych"
            elif sim <= self._band_low:
                proto_domain = "general"
            # else: in margin → LLM decides

        # 3) Decide: prototype-confident path vs LLM-verifier path.
        result = self._decide(
            text=text,
            title=title,
            similarity=sim,
            prototype_domain=proto_domain,
            prototype_available=prototype_available,
        )

        self._cache_put(cache_key, result, conn=conn)
        return result

    # ── Batched API (high-throughput maintenance / bulk ingest) ──────
    def classify_many(
        self,
        items: list,
        *,
        conn: Optional["sqlite3.Connection"] = None,
    ) -> list:
        """Vectorised counterpart to :meth:`classify` for bulk workloads.

        Same semantics per item, but **all uncached candidates are
        embedded in a single GPU batch** — turns ``N×`` ``encode(1)`` calls
        into ``1×`` ``encode(N)``. For an 800M-param embedder the speedup
        is typically 30–80×, and GPU utilisation finally saturates.

        The LLM verifier is *not* batched (llama.cpp / structured-output
        wrappers run per-prompt); margin-band and safety calls remain
        sequential. That's still net-faster because the embedding step
        dominates wall time when the LLM is bypassed (clear-domain docs).

        Parameters
        ----------
        items
            List of ``(text, title)`` tuples. ``title`` may be ``None``.
        conn
            Optional caller-owned SQLite connection. Threaded through
            to cache reads/writes so the bulk workload does not contend
            with its own active write transaction (see :meth:`classify`).

        Returns
        -------
        list
            ``ClassificationResult`` objects in the **same order** as
            ``items``. Cache hits are returned directly. Errors raise —
            no partial results, no silent fallback.
        """
        if not items:
            return []

        n = len(items)
        results: list = [None] * n

        # ── Phase 1: cache lookup ──────────────────────────────────
        cache_keys: list = [None] * n
        pending_idx: list = []
        for i, (text, title) in enumerate(items):
            if not isinstance(text, str) or not text.strip():
                raise ValueError(
                    f"ContentClassifier.classify_many: items[{i}].text "
                    "must be a non-empty string"
                )
            key = self._cache_key(text, title=title)
            cache_keys[i] = key
            cached = self._cache_get(key, conn=conn)
            if cached is not None:
                results[i] = cached
            else:
                pending_idx.append(i)

        if not pending_idx:
            return results

        # ── Phase 2: prototype + ONE embedding batch for all uncached ─
        prototype_available = self._ensure_prototype()
        sims: list = [None] * n  # type: ignore[var-annotated]
        proto_domains: list = [None] * n  # type: ignore[var-annotated]

        if prototype_available:
            excerpts = [items[i][0][: self._LLM_CONTEXT_BYTES] for i in pending_idx]
            # Single GPU call — saturates the device.
            batch_emb = self._embeddings.embed_texts(excerpts)
            # Both sides L2-normalised → cosine = dot product.
            cos = batch_emb @ self._psych_prototype  # shape (len(pending),)
            for slot, i in enumerate(pending_idx):
                s = float(cos[slot])
                sims[i] = s
                if s >= self._band_high:
                    proto_domains[i] = "psych"
                elif s <= self._band_low:
                    proto_domains[i] = "general"
                # else: in margin → LLM

        # ── Phase 3: per-item _decide (LLM calls remain sequential) ──
        for i in pending_idx:
            text, title = items[i]
            verdict = self._decide(
                text=text,
                title=title,
                similarity=sims[i],
                prototype_domain=proto_domains[i],
                prototype_available=prototype_available,
            )
            self._cache_put(cache_keys[i], verdict, conn=conn)
            results[i] = verdict

        return results

    # ── Decision branches ────────────────────────────────────────────
    def _decide(
        self,
        *,
        text: str,
        title: Optional[str],
        similarity: Optional[float],
        prototype_domain: Optional[str],
        prototype_available: bool,
    ) -> ClassificationResult:
        if prototype_domain is not None and self._llm is None:
            # Prototype-confident, no LLM → use prototype, safe-default.
            assert similarity is not None
            return ClassificationResult(
                corpus_domain=prototype_domain,
                safety_flag="safe",
                confidence=self._sim_to_confidence(similarity, prototype_domain),
                method="prototype",
                reasoning=None,
                similarity=similarity,
            )

        if self._llm is not None:
            try:
                llm_verdict = self._llm_classify(text=text, title=title)
            except LLMVerificationError:
                # If we already have a confident prototype verdict the
                # only thing the LLM contributes is the safety_flag.
                # Falling back to the prototype-only path (safe-default)
                # is exactly what the "no LLM wired" branch above does
                # and is preferable to killing the whole batch over a
                # transient llama.cpp crash. Without a prototype verdict
                # we have nothing to anchor on → re-raise.
                if prototype_domain is None:
                    raise
                logger.warning(
                    "ContentClassifier: LLM verification failed in hybrid "
                    "path (sim=%.3f, proto=%s) — degrading to prototype-"
                    "only with safety_flag='safe'.",
                    similarity, prototype_domain,
                )
                assert similarity is not None
                return ClassificationResult(
                    corpus_domain=prototype_domain,
                    safety_flag="safe",
                    confidence=self._sim_to_confidence(similarity, prototype_domain),
                    method="prototype",
                    reasoning=None,
                    similarity=similarity,
                )
            if prototype_domain is not None:
                # Hybrid: prototype handles domain, LLM contributes safety.
                # If LLM disagrees on domain we *log* but keep prototype —
                # the prototype is the stable, auditable signal.
                if llm_verdict.corpus_domain != prototype_domain:
                    logger.info(
                        "ContentClassifier: LLM domain (%s) disagrees with "
                        "prototype (%s, sim=%.3f) — keeping prototype.",
                        llm_verdict.corpus_domain, prototype_domain, similarity,
                    )
                assert similarity is not None
                return ClassificationResult(
                    corpus_domain=prototype_domain,
                    safety_flag=llm_verdict.safety_flag,
                    confidence=self._sim_to_confidence(similarity, prototype_domain),
                    method="hybrid",
                    similarity=similarity,
                )
            # Pure-LLM path: prototype unavailable or inside margin band.
            return ClassificationResult(
                corpus_domain=llm_verdict.corpus_domain,
                safety_flag=llm_verdict.safety_flag,
                # No similarity-based confidence, but the LLM was certain
                # enough to commit to a Literal value → 0.7 baseline.
                confidence=0.7,
                method="llm",
                similarity=similarity,
            )

        # Neither prototype-confident nor LLM available.
        if not prototype_available:
            raise RuntimeError(
                "ContentClassifier.classify: cannot determine domain — "
                f"psych prototype unavailable (need >= {self._MIN_PSYCH_CHUNKS} "
                "psych-tagged chunks) AND no llm_wrapper was provided. "
                "Either bootstrap the psych corpus first or pass a "
                "LLMStructuredWrapper to the classifier."
            )
        # Prototype available but in margin band, no LLM to break tie.
        # Refuse to guess — surface as error instead of silent default.
        raise RuntimeError(
            f"ContentClassifier.classify: prototype similarity={similarity:.3f} "
            f"falls in ambiguous band [{self._band_low}, {self._band_high}] "
            "and no LLM is wired to verify. Provide an llm_wrapper or widen "
            "the band — silent fallback would mistag content."
        )

    # ── Prototype management ─────────────────────────────────────────
    def _ensure_prototype(self) -> bool:
        """Build or refresh the psych prototype.

        Returns ``True`` if the prototype is available, ``False`` if
        the psych corpus is too small (chunks below ``_MIN_PSYCH_CHUNKS``).
        Refresh triggers when the psych chunk count has grown by more
        than ``_PROTOTYPE_REFRESH_GROWTH``.
        """
        with self._prototype_lock:
            current_count = self._count_wellbeing_chunks()
            if current_count < self._MIN_PSYCH_CHUNKS:
                if self._psych_prototype is not None:
                    # Corpus shrank? unusual, but invalidate.
                    self._psych_prototype = None
                    self._psych_chunk_count = 0
                return False

            need_build = self._psych_prototype is None
            if not need_build and self._psych_chunk_count > 0:
                growth = (current_count - self._psych_chunk_count) / max(
                    1, self._psych_chunk_count
                )
                if growth >= self._PROTOTYPE_REFRESH_GROWTH:
                    need_build = True

            if need_build:
                self._psych_prototype = self._build_prototype()
                self._psych_chunk_count = current_count
                logger.info(
                    "ContentClassifier: built psych prototype from %d chunks "
                    "(dim=%d)",
                    current_count, self._psych_prototype.shape[0],
                )
            return self._psych_prototype is not None

    def _count_wellbeing_chunks(self) -> int:
        conn = self._db.get_connection()
        try:
            cur = conn.cursor()
            row = cur.execute(
                "SELECT COUNT(*) FROM chunks WHERE domain = 'psych'"
            ).fetchone()
            cur.close()
            return int(row[0]) if row else 0
        finally:
            self._db.return_connection(conn)

    def _build_prototype(self) -> np.ndarray:
        """Mean-of-normalised-embeddings over all psych chunks.

        We rely on chunks being stored as raw float32 bytes (the same
        layout :class:`UnifiedRagStore.upsert_documents` writes). After
        averaging we re-normalise so the prototype sits on the unit
        sphere — that way ``np.dot(prototype, candidate)`` is cosine
        similarity for L2-normalised candidates.
        """
        conn = self._db.get_connection()
        try:
            cur = conn.cursor()
            rows = cur.execute(
                "SELECT embedding FROM chunks WHERE domain = 'psych'"
            ).fetchall()
            cur.close()
        finally:
            self._db.return_connection(conn)

        if not rows:
            raise RuntimeError(
                "ContentClassifier._build_prototype: no psych chunks found, "
                "but _count_wellbeing_chunks reported >0 — concurrent deletion?"
            )

        dim = self._embeddings.dimension
        accumulator = np.zeros(dim, dtype=np.float64)
        valid = 0
        for (blob,) in rows:
            try:
                vec = np.frombuffer(blob, dtype=np.float32)
                if vec.shape[0] != dim:
                    continue
                accumulator += vec.astype(np.float64)
                valid += 1
            except (TypeError, ValueError):
                continue

        if valid == 0:
            raise RuntimeError(
                "ContentClassifier._build_prototype: all psych embeddings "
                "are corrupt or have wrong dimensionality"
            )

        prototype = accumulator / valid
        norm = float(np.linalg.norm(prototype))
        if norm < 1e-9:
            raise RuntimeError(
                "ContentClassifier._build_prototype: prototype norm collapsed "
                "to zero — psych embeddings cancel out, indicating broken data"
            )
        prototype = prototype / norm
        return prototype.astype(np.float32)

    def _prototype_similarity(self, text: str) -> float:
        """Cosine similarity of ``text`` against the psych prototype."""
        if self._psych_prototype is None:
            raise RuntimeError("_prototype_similarity called without prototype")
        # Use up to LLM_CONTEXT_BYTES — the prototype-relevant signal is
        # in the head of the document, not the footer/navigation.
        excerpt = text[: self._LLM_CONTEXT_BYTES]
        candidate = self._embeddings.embed_query(excerpt)
        # Both vectors are L2-normalised → cosine == dot.
        return float(np.dot(self._psych_prototype, candidate))

    @staticmethod
    def _sim_to_confidence(similarity: float, domain: str) -> float:
        """Map cosine similarity → [0,1] classification confidence.

        For ``psych``: confidence = clamp((sim - 0.5) / 0.4, 0, 1) so
        sim=0.5 → 0.0, sim=0.9 → 1.0.
        For ``general``: mirrored about 0.5.
        """
        if domain == "psych":
            return max(0.0, min(1.0, (similarity - 0.5) / 0.4))
        # general
        return max(0.0, min(1.0, (0.5 - similarity) / 0.4))

    # ── LLM verifier ─────────────────────────────────────────────────
    def _llm_classify(
        self, *, text: str, title: Optional[str]
    ) -> _ContentClassificationLLM:
        excerpt = text[: self._LLM_CONTEXT_BYTES]
        title_line = f"TITLE: {title}\n" if title else ""
        prompt = (
            "You are classifying a document for a Retrieval-Augmented "
            "Generation pipeline that serves both general questions and "
            "clinical-psychology / mental-health support queries.\n\n"
            "Decide TWO labels for the document below.\n\n"
            "1) corpus_domain — exactly one of:\n"
            "   • 'psych'   — clinical psychology, psychiatry, psychotherapy, "
            "mental-health education, emotional-wellbeing content, evidence-"
            "based therapy techniques, diagnostic literature.\n"
            "   • 'general' — everything else (general knowledge, news, "
            "technology, lifestyle, science outside mental health).\n\n"
            "2) safety_flag — exactly one of:\n"
            "   • 'safe'      — ordinary content, no acute-harm material.\n"
            "   • 'sensitive' — discusses crisis topics (self-harm, suicide, "
            "abuse, severe trauma) in a clinical / educational / supportive "
            "tone.\n"
            "   • 'crisis'    — gives methods, instructions, or encouragement "
            "for self-harm or suicide; must NEVER surface as supporting "
            "context. Reserve this label for clearly harmful material.\n\n"
            f"{title_line}DOCUMENT:\n{excerpt}\n"
        )

        # The wrapper compiles ``_ContentClassificationLLM``'s JSON
        # Schema into a GBNF grammar and constrains llama.cpp's sampler
        # to it: the model can *only* emit the literal JSON skeleton
        # plus one of the schema's enum values per field. That makes
        # markdown fences, prose preambles, and thought-channel tokens
        # physically unsampleable, so the system prompt no longer needs
        # to negotiate with the model about output format \u2014 it just
        # primes role.
        system_prompt = (
            "You are a strict document classifier. "
            "Decide the corpus domain and safety flag for the document "
            "the user supplies."
        )
        try:
            verdict = self._llm.generate_structured(
                prompt=prompt,
                output_schema=_ContentClassificationLLM,
                max_tokens=self._LLM_MAX_TOKENS,
                system_prompt=system_prompt,
            )
        except Exception as exc:
            # Re-raise with a typed message so callers can decide whether
            # to fall back to prototype-only or surface the error.
            raise LLMVerificationError(
                f"ContentClassifier: LLM verification failed: {exc}"
            ) from exc

        # Whitelist enforcement (Pydantic Literal already checks, but be
        # defensive in case a future schema relaxation slips through).
        if verdict.corpus_domain not in _VALID_DOMAINS:
            raise LLMVerificationError(
                f"ContentClassifier: LLM returned invalid corpus_domain="
                f"{verdict.corpus_domain!r}"
            )
        if verdict.safety_flag not in _VALID_SAFETY:
            raise LLMVerificationError(
                f"ContentClassifier: LLM returned invalid safety_flag="
                f"{verdict.safety_flag!r}"
            )
        return verdict

    # ── Cache I/O ────────────────────────────────────────────────────
    def _cache_key(self, text: str, *, title: Optional[str]) -> str:
        head = (title or "").encode("utf-8") + b"\n" + text.encode("utf-8")[
            : self._CACHE_INPUT_BYTES
        ]
        return hashlib.sha256(head).hexdigest()

    def _cache_get(
        self,
        content_hash: str,
        *,
        conn: Optional[sqlite3.Connection] = None,
    ) -> Optional[ClassificationResult]:
        """Look up a cached verdict.

        Parameters
        ----------
        conn
            Optional pre-existing connection. When the caller already
            owns an active transaction (e.g. the maintenance reclassifier
            holds a write transaction across the batch), passing it here
            avoids opening a second connection that would block on
            SQLite's single-writer constraint and time out on
            ``busy_timeout``.
        """
        owns_conn = conn is None
        if owns_conn:
            conn = self._db.get_connection()
        try:
            cur = conn.cursor()
            try:
                row = cur.execute(
                    "SELECT corpus_domain, safety_flag, confidence, method "
                    "FROM content_classification_cache WHERE content_hash = ?",
                    (content_hash,),
                ).fetchone()
            finally:
                cur.close()
        finally:
            if owns_conn:
                self._db.return_connection(conn)

        if row is None:
            return None
        return ClassificationResult(
            corpus_domain=str(row[0]),
            safety_flag=str(row[1]),
            confidence=float(row[2]),
            method="cached",
            reasoning=None,
            similarity=None,
        )

    def _cache_put(
        self,
        content_hash: str,
        result: ClassificationResult,
        *,
        conn: Optional[sqlite3.Connection] = None,
    ) -> None:
        """Persist a verdict.

        When ``conn`` is provided the INSERT joins the caller's open
        transaction (and is committed atomically with the caller's other
        writes); when omitted, this method opens its own connection and
        commits immediately. The shared-connection path is what allows
        the maintenance reclassifier to populate the cache without
        contending with its own batched ``UPDATE`` transaction.
        """
        if result.method == "cached":
            return  # nothing to write

        owns_conn = conn is None
        if owns_conn:
            conn = self._db.get_connection()
        try:
            cur = conn.cursor()
            try:
                cur.execute(
                    "INSERT OR REPLACE INTO content_classification_cache "
                    "(content_hash, corpus_domain, safety_flag, confidence, "
                    " method, created_at) VALUES (?, ?, ?, ?, ?, ?)",
                    (
                        content_hash,
                        result.corpus_domain,
                        result.safety_flag,
                        float(result.confidence),
                        result.method,
                        datetime.now(timezone.utc).isoformat(),
                    ),
                )
            finally:
                cur.close()
            if owns_conn:
                conn.commit()
        finally:
            if owns_conn:
                self._db.return_connection(conn)


__all__ = [
    "ContentClassifier",
    "ClassificationResult",
]
